language: rust
cache: cargo
rust:
    - stable
    - beta
jobs:
    include:
        - name: "Nightly: step trait"
          rust: nightly
          script:
              - cargo test --all --features examples,serde,step_trait

script:
    - cargo test --all --features examples,serde
