[package]
name = "bounded-integer"
version = "0.3.0"
authors = ["Kestrer <kestrer.dev@gmail.com>"]
description = "Bounded integers"
keywords = ["bounded", "integer", "macro", "refinement"]
license = "ISC"
repository = "https://github.com/Kestrer/bounded-integer"
readme = "README.md"
edition = "2018"

[dependencies]
bounded-integer-macro = { path = "./macro", version = "0.3.0" }

serde_crate = { package = "serde", version = "1.0.117", default-features = false, optional = true }

[features]
examples = []
serde = ["serde_crate", "bounded-integer-macro/serde"]
step_trait = ["bounded-integer-macro/step_trait"]

[package.metadata.docs.rs]
features = ["examples"]

[workspace]
members = ["macro"]
