[package]
name = "bounded-integer"
version = "0.2.1"
authors = ["Koxiaet <38139193+Koxiaet@users.noreply.github.com>"]
description = "Bounded integers"
keywords = ["bounded", "integer", "macro", "refinement"]
license = "ISC"
repository = "https://github.com/Koxiaet/bounded-integer"
readme = "README.md"
edition = "2018"

[dependencies]
bounded-integer-macro = { version = "0.2", path = "macro" }

[features]
examples = []

[package.metadata.docs.rs]
features = ["examples"]
