[package]
name = "bounded-integer-plugin"
version = "0.0.0"
authors = ["Curtis McEnroe <programble@gmail.com>"]

[lib]
plugin = true

[dev-dependencies]
bounded-integer = { path = "../bounded-integer" }
